version: "3.7"

services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - mongodb_data:/data/db
    #restart: "on-failure"
    restart: always

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - os_data:/usr/share/opensearch/data
    #restart: "on-failure"
    restart: always

  graylog:
    #hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.1}"
    depends_on:
      - opensearch
      - mongodb
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      TZ: Europe/Madrid
      GRAYLOG_ROOT_TIMEZONE: "Europe/Madrid"
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      #GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      #GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_PASSWORD_SECRET: "FgNZNp66FNyxkNmTprDkAQacXQCeer0gS0wXZMkQowdTm75R2hlSKtx3dbKycl0CuctWBpwXZzf8cyq8tmcwjhqLP0eSwAUm"
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9001"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9001ยบ/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW TCP
    - "9001:9001/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
      - graylog_data:/usr/share/graylog/data/data
      - graylog_journal:/usr/share/graylog/data/journal
      - graylog_plugin:/usr/share/graylog/plugin
    #restart: "on-failure"
    restart: always

volumes:
  mongodb_data:
    driver: local
  os_data:
    driver: local 
  graylog_data:
    driver: local 
  graylog_journal:
    driver: local
  graylog_plugin:
    driver: local

